### ISSUE TITLE
cannot find -lrace

### ISSUE THREAD

**Issue by vyacheslavslava** [racepwn/racepwn#1]
Привет :)
Не могу установить вашу утилиту  
```
# ./build.sh
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/racepwn
make: *** No targets specified and no makefile found.  Stop.
# _/home/ubuntu/racepwn/racepwn/race
/usr/bin/ld: cannot find -lrace
collect2: error: ld returned 1 exit status
```
Ubuntu server 18.04
Все зависимости из описания установил

Помогите пож)))))))

**Comment by mikhailbadin** [comment]
Добрый день, Вячеслав!

Мы планируем в ближайшее время переписать скрипт сборки, т.к. с ней есть некоторые проблемы (даже молчу о кроссплатформенности).
По времени займёт пару дней. Как допилим, сразу сообщу. 
Сорри за временные неудобства.

**Comment by vyacheslavslava** [comment]
Спасибо 👍 
А можете сказать, на какой оси можно сейчас собрать ваше чудо? 
Очень хочется опробовать

**Comment by mikhailbadin** [comment]
Попробуйте собрать еще раз.
Проверьте все зависимости, пересоберите и пожалуйста сообщите о результате.

Сейчас должно собираться без проблем на любом популярном linux дистрибутиве.

**Comment by vyacheslavslava** [comment]
Работает, спасибо
