### ISSUE TITLE
Getting error while installing ./build.sh 

### ISSUE THREAD

**Issue by shripad5258** [racepwn/racepwn#14]
![Screenshot from 2021-03-09 12-50-51](https://user-images.githubusercontent.com/65358061/110433226-2d854f00-80d6-11eb-8b66-8f79d64bebf0.png)

**Comment by mikhailbadin** [comment]
Is openssl-dev library installed before './build.sh' was launched?

**Comment by shripad5258** [comment]
Thanks 
i was reinstall openssl-dev library and then problem is solved.
thnks
