### ISSUE TITLE
[macbook M1] race/race.go:91:15: _Ctype_struct_race_info_s can't be allocated in Go; it is incomplete (or unallocatable)

### ISSUE THREAD

**Issue by cyal1** [racepwn/racepwn#15]
race/race.go:91:15: _Ctype_struct_race_info_s can't be allocated in Go; it is incomplete (or unallocatable)

**Comment by mikhailbadin** [comment]
Hello! I don't have M1 macbook. I will try to reproduce this error, but it's takes a lot of time.

**Comment by MatnazaroFF** [comment]
Hello @mikhailbadin, I have the exact same issue with compilation on Docker container.
p.s OS is Windows 11

**Comment by cyal1** [comment]
It seems to be related to the go version

**Comment by cyal1** [comment]
> It seems to be related to the go version

golang 1.17.2 will encounter this problem

**Comment by cyal1** [comment]
> > It seems to be related to the go version
> 
> golang 1.17.2 will encounter this problem

@mikhailbadin

**Comment by cyal1** [comment]
https://github.com/golang/go/issues/43146
